document.write("<ul>");
document.write("<li><a href='index.html'>Home</a></li>");
document.write("<li><a href='download.html'>Download</a></li>");
document.write("<li>Resources");
document.write("<ul>");
document.write("<li><a href='http://www.antlr.org/wiki/display/ST4/Introduction'>Introduction</a></li>");
document.write("<li><a href='http://www.antlr.org/wiki/display/ST4/StringTemplate+4+Documentation'>Documentation v4</a></li>");
document.write("<li><a href='http://www.antlr.org/wiki/display/ST/StringTemplate+3+Documentation'>Documentation v3</a></li>");
document.write("<li><a href='articles.html'>Articles</a></li>");
document.write("<li><a href='api/index.html'>Runtime API v4</a></li>");
document.write("<li><a href='api3/index.html'>Runtime API v3</a></li>");
document.write("<li><a href='https://github.com/antlr/stringtemplate4'>Source</a></li>");
document.write("<li><a href='http://www.antlr.org/wiki/display/ST4/StringTemplate+FAQ'>FAQ</a></li>");
document.write("</ul></li>");
document.write("<li><a href='about.html'>About StringTemplate</a></li>");
document.write("<li><a href='license.html'>License and contributions</a></li>");
document.write("<li><a href='support.html'>Support</a></li>");
document.write("<li><a href='https://github.com/antlr/stringtemplate4/issues'>Bugs</a></li>");
document.write("<li><a href='mailto:parrt@antlr.org?subject=[insert subject here]'>Contact</a></li>");
document.write("<li><a href='credits.html'>Credits</a></li>");
document.write("<li><a href='http://www.antlr.org'>ANTLR</a></li>");
document.write("</ul>");
